version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache: #Download and cache dependencies
          keys:
            - v1-dependencies-npm-{{ checksum "package-lock.json" }}
            - v1-dependencies-npm

      - run: npm ci

      # run tests!
      - run: mv config/bim.env.js.test config/bim.env.js
      - run: npm run cypress:install
      - run: npm run cypress:test

      - save_cache:
          key: v1-dependencies-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
            - ~/.npm
            - ~/.cache